# Node docker image on which this would be run
image: node:8.10.0

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy_production

# Job 1:
Test:
  stage: test
  script:
    - npm install
    - npm run test

# Job 2:
# Deploy to staging
Production:
  image: ruby:latest
  only:
    - master
  stage: deploy_production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=fast-badlands-02069 --api-key=bf7268bf-0f30-41e7-ae4c-49c363d92173